'use strict';(function(){var browserFakeUserAgent='Fake/5.0 (FakeOS) AppleWebKit/123 (KHTML, like Gecko) Fake/12.3.4567.89 Fake/123.45';var isNodejs=typeof process==='object'&&typeof process.versions==='object'&&process.versions.node&&!process.browser;if(isNodejs){var version=process.versions.node.toString().replace('v','');browserFakeUserAgent='Nodejs/'+version+' (NodeOS) AppleWebKit/'+version+' (KHTML, like Gecko) Nodejs/'+version+' Nodejs/'+version}(function(that){if(typeof window!=='undefined'){return}
if(typeof window==='undefined'&&typeof global!=='undefined'){global.navigator={userAgent:browserFakeUserAgent,getUserMedia:function(){}};that.window=global}else if(typeof window==='undefined'){}
if(typeof location==='undefined'){that.location={protocol:'file:',href:'',hash:''}}
if(typeof screen==='undefined'){that.screen={width:0,height:0}}})(typeof global!=='undefined'?global:window);var navigator=window.navigator;if(typeof navigator!=='undefined'){if(typeof navigator.webkitGetUserMedia!=='undefined'){navigator.getUserMedia=navigator.webkitGetUserMedia}
if(typeof navigator.mozGetUserMedia!=='undefined'){navigator.getUserMedia=navigator.mozGetUserMedia}}else{navigator={getUserMedia:function(){},userAgent:browserFakeUserAgent}}
var isMobileDevice=!!(/Android|webOS|iPhone|iPad|iPod|BB10|BlackBerry|IEMobile|Opera Mini|Mobile|mobile/i.test(navigator.userAgent||''));var isEdge=navigator.userAgent.indexOf('Edge')!==-1&&(!!navigator.msSaveOrOpenBlob||!!navigator.msSaveBlob);var isOpera=!!window.opera||navigator.userAgent.indexOf(' OPR/')>=0;var isFirefox=typeof window.InstallTrigger!=='undefined';var isSafari=Object.prototype.toString.call(window.HTMLElement).indexOf('Constructor')>0;var isChrome=!!window.chrome&&!isOpera;var isIE=typeof document!=='undefined'&&!!document.documentMode&&!isEdge;function getBrowserInfo(){var nVer=navigator.appVersion;var nAgt=navigator.userAgent;var browserName=navigator.appName;var fullVersion=''+parseFloat(navigator.appVersion);var majorVersion=parseInt(navigator.appVersion,10);var nameOffset,verOffset,ix;if(isOpera){browserName='Opera';try{fullVersion=navigator.userAgent.split('OPR/')[1].split(' ')[0];majorVersion=fullVersion.split('.')[0]}catch(e){fullVersion='0.0.0.0';majorVersion=0}}
else if(isIE){verOffset=nAgt.indexOf('MSIE');browserName='IE';fullVersion=nAgt.substring(verOffset+5)}
else if(isChrome){verOffset=nAgt.indexOf('Chrome');browserName='Chrome';fullVersion=nAgt.substring(verOffset+7)}
else if(isSafari){verOffset=nAgt.indexOf('Safari');browserName='Safari';fullVersion=nAgt.substring(verOffset+7);if((verOffset=nAgt.indexOf('Version'))!==-1){fullVersion=nAgt.substring(verOffset+8)}}
else if(isFirefox){verOffset=nAgt.indexOf('Firefox');browserName='Firefox';fullVersion=nAgt.substring(verOffset+8)}
else if((nameOffset=nAgt.lastIndexOf(' ')+1)<(verOffset=nAgt.lastIndexOf('/'))){browserName=nAgt.substring(nameOffset,verOffset);fullVersion=nAgt.substring(verOffset+1);if(browserName.toLowerCase()===browserName.toUpperCase()){browserName=navigator.appName}}
if(isEdge){browserName='Edge';fullVersion=parseInt(navigator.userAgent.match(/Edge\/(\d+).(\d+)$/)[2],10).toString()}
if((ix=fullVersion.indexOf(';'))!==-1){fullVersion=fullVersion.substring(0,ix)}
if((ix=fullVersion.indexOf(' '))!==-1){fullVersion=fullVersion.substring(0,ix)}
majorVersion=parseInt(''+fullVersion,10);if(isNaN(majorVersion)){fullVersion=''+parseFloat(navigator.appVersion);majorVersion=parseInt(navigator.appVersion,10)}
return{fullVersion:fullVersion,version:majorVersion,name:browserName,isPrivateBrowsing:!1}}
function retry(isDone,next){var currentTrial=0,maxRetry=50,interval=10,isTimeout=!1;var id=window.setInterval(function(){if(isDone()){window.clearInterval(id);next(isTimeout)}
if(currentTrial++>maxRetry){window.clearInterval(id);isTimeout=!0;next(isTimeout)}},10)}
function isIE10OrLater(userAgent){var ua=userAgent.toLowerCase();if(ua.indexOf('msie')===0&&ua.indexOf('trident')===0){return!1}
var match=/(?:msie|rv:)\s?([\d\.]+)/.exec(ua);if(match&&parseInt(match[1],10)>=10){return!0}
return!1}
function detectPrivateMode(callback){var isPrivate;try{if(window.webkitRequestFileSystem){window.webkitRequestFileSystem(window.TEMPORARY,1,function(){isPrivate=!1},function(e){isPrivate=!0})}else if(window.indexedDB&&/Firefox/.test(window.navigator.userAgent)){var db;try{db=window.indexedDB.open('test');db.onerror=function(){return!0}}catch(e){isPrivate=!0}
if(typeof isPrivate==='undefined'){retry(function isDone(){return db.readyState==='done'?!0:!1},function next(isTimeout){if(!isTimeout){isPrivate=db.result?!1:!0}})}}else if(isIE10OrLater(window.navigator.userAgent)){isPrivate=!1;try{if(!window.indexedDB){isPrivate=!0}}catch(e){isPrivate=!0}}else if(window.localStorage&&/Safari/.test(window.navigator.userAgent)){try{window.localStorage.setItem('test',1)}catch(e){isPrivate=!0}
if(typeof isPrivate==='undefined'){isPrivate=!1;window.localStorage.removeItem('test')}}}catch(e){isPrivate=!1}
retry(function isDone(){return typeof isPrivate!=='undefined'?!0:!1},function next(isTimeout){callback(isPrivate)})}
var isMobile={Android:function(){return navigator.userAgent.match(/Android/i)},BlackBerry:function(){return navigator.userAgent.match(/BlackBerry|BB10/i)},iOS:function(){return navigator.userAgent.match(/iPhone|iPad|iPod/i)},Opera:function(){return navigator.userAgent.match(/Opera Mini/i)},Windows:function(){return navigator.userAgent.match(/IEMobile/i)},any:function(){return(isMobile.Android()||isMobile.BlackBerry()||isMobile.iOS()||isMobile.Opera()||isMobile.Windows())},getOsName:function(){var osName='Unknown OS';if(isMobile.Android()){osName='Android'}
if(isMobile.BlackBerry()){osName='BlackBerry'}
if(isMobile.iOS()){osName='iOS'}
if(isMobile.Opera()){osName='Opera Mini'}
if(isMobile.Windows()){osName='Windows'}
return osName}};function detectDesktopOS(){var unknown='-';var nVer=navigator.appVersion;var nAgt=navigator.userAgent;var os=unknown;var clientStrings=[{s:'Windows 10',r:/(Windows 10.0|Windows NT 10.0)/},{s:'Windows 8.1',r:/(Windows 8.1|Windows NT 6.3)/},{s:'Windows 8',r:/(Windows 8|Windows NT 6.2)/},{s:'Windows 7',r:/(Windows 7|Windows NT 6.1)/},{s:'Windows Vista',r:/Windows NT 6.0/},{s:'Windows Server 2003',r:/Windows NT 5.2/},{s:'Windows XP',r:/(Windows NT 5.1|Windows XP)/},{s:'Windows 2000',r:/(Windows NT 5.0|Windows 2000)/},{s:'Windows ME',r:/(Win 9x 4.90|Windows ME)/},{s:'Windows 98',r:/(Windows 98|Win98)/},{s:'Windows 95',r:/(Windows 95|Win95|Windows_95)/},{s:'Windows NT 4.0',r:/(Windows NT 4.0|WinNT4.0|WinNT|Windows NT)/},{s:'Windows CE',r:/Windows CE/},{s:'Windows 3.11',r:/Win16/},{s:'Android',r:/Android/},{s:'Open BSD',r:/OpenBSD/},{s:'Sun OS',r:/SunOS/},{s:'Linux',r:/(Linux|X11)/},{s:'iOS',r:/(iPhone|iPad|iPod)/},{s:'Mac OS X',r:/Mac OS X/},{s:'Mac OS',r:/(MacPPC|MacIntel|Mac_PowerPC|Macintosh)/},{s:'QNX',r:/QNX/},{s:'UNIX',r:/UNIX/},{s:'BeOS',r:/BeOS/},{s:'OS/2',r:/OS\/2/},{s:'Search Bot',r:/(nuhk|Googlebot|Yammybot|Openbot|Slurp|MSNBot|Ask Jeeves\/Teoma|ia_archiver)/}];for(var i=0,cs;cs=clientStrings[i];i++){if(cs.r.test(nAgt)){os=cs.s;break}}
var osVersion=unknown;if(/Windows/.test(os)){if(/Windows (.*)/.test(os)){osVersion=/Windows (.*)/.exec(os)[1]}
os='Windows'}
switch(os){case 'Mac OS X':if(/Mac OS X (10[\.\_\d]+)/.test(nAgt)){osVersion=/Mac OS X (10[\.\_\d]+)/.exec(nAgt)[1]}
break;case 'Android':if(/Android ([\.\_\d]+)/.test(nAgt)){osVersion=/Android ([\.\_\d]+)/.exec(nAgt)[1]}
break;case 'iOS':if(/OS (\d+)_(\d+)_?(\d+)?/.test(nAgt)){osVersion=/OS (\d+)_(\d+)_?(\d+)?/.exec(nVer);osVersion=osVersion[1]+'.'+osVersion[2]+'.'+(osVersion[3]|0)}
break}
return{osName:os,osVersion:osVersion}}
var osName='Unknown OS';var osVersion='Unknown OS Version';function getAndroidVersion(ua){ua=(ua||navigator.userAgent).toLowerCase();var match=ua.match(/android\s([0-9\.]*)/);return match?match[1]:!1}
var osInfo=detectDesktopOS();if(osInfo&&osInfo.osName&&osInfo.osName!='-'){osName=osInfo.osName;osVersion=osInfo.osVersion}else if(isMobile.any()){osName=isMobile.getOsName();if(osName=='Android'){osVersion=getAndroidVersion()}}
var isNodejs=typeof process==='object'&&typeof process.versions==='object'&&process.versions.node;if(osName==='Unknown OS'&&isNodejs){osName='Nodejs';osVersion=process.versions.node.toString().replace('v','')}
var isCanvasSupportsStreamCapturing=!1;var isVideoSupportsStreamCapturing=!1;['captureStream','mozCaptureStream','webkitCaptureStream'].forEach(function(item){if(typeof document==='undefined'||typeof document.createElement!=='function'){return}
if(!isCanvasSupportsStreamCapturing&&item in document.createElement('canvas')){isCanvasSupportsStreamCapturing=!0}
if(!isVideoSupportsStreamCapturing&&item in document.createElement('video')){isVideoSupportsStreamCapturing=!0}});function DetectLocalIPAddress(callback){if(!DetectRTC.isWebRTCSupported){return}
if(DetectRTC.isORTCSupported){return}
getIPs(function(ip){if(ip.match(/^(192\.168\.|169\.254\.|10\.|172\.(1[6-9]|2\d|3[01]))/)){callback('Local: '+ip)}
else{callback('Public: '+ip)}})}
function getIPs(callback){if(typeof document==='undefined'||typeof document.getElementById!=='function'){return}
var ipDuplicates={};var RTCPeerConnection=window.RTCPeerConnection||window.mozRTCPeerConnection||window.webkitRTCPeerConnection;var useWebKit=!!window.webkitRTCPeerConnection;if(!RTCPeerConnection){var iframe=document.getElementById('iframe');if(!iframe){throw 'NOTE: you need to have an iframe in the page right above the script tag.'}
var win=iframe.contentWindow;RTCPeerConnection=win.RTCPeerConnection||win.mozRTCPeerConnection||win.webkitRTCPeerConnection;useWebKit=!!win.webkitRTCPeerConnection}
if(!RTCPeerConnection){return}
var mediaConstraints={optional:[{RtpDataChannels:!0}]};var servers;if(useWebKit){servers={iceServers:[{urls:'stun:stun.services.mozilla.com'}]};if(typeof DetectRTC!=='undefined'&&DetectRTC.browser.isFirefox&&DetectRTC.browser.version<=38){servers[0]={url:servers[0].urls}}}
var pc=new RTCPeerConnection(servers,mediaConstraints);function handleCandidate(candidate){var ipRegex=/([0-9]{1,3}(\.[0-9]{1,3}){3})/;var match=ipRegex.exec(candidate);if(!match){console.warn('Could not match IP address in',candidate);return}
var ipAddress=match[1];if(ipDuplicates[ipAddress]===undefined){callback(ipAddress)}
ipDuplicates[ipAddress]=!0}
pc.onicecandidate=function(ice){if(ice.candidate){handleCandidate(ice.candidate.candidate)}};pc.createDataChannel('');pc.createOffer(function(result){pc.setLocalDescription(result,function(){},function(){})},function(){});setTimeout(function(){var lines=pc.localDescription.sdp.split('\n');lines.forEach(function(line){if(line.indexOf('a=candidate:')===0){handleCandidate(line)}})},1000)}
var MediaDevices=[];var audioInputDevices=[];var audioOutputDevices=[];var videoInputDevices=[];if(navigator.mediaDevices&&navigator.mediaDevices.enumerateDevices){navigator.enumerateDevices=function(callback){navigator.mediaDevices.enumerateDevices().then(callback).catch(function(){callback([])})}}
var canEnumerate=!1;if(typeof MediaStreamTrack!=='undefined'&&'getSources' in MediaStreamTrack){canEnumerate=!0}else if(navigator.mediaDevices&&!!navigator.mediaDevices.enumerateDevices){canEnumerate=!0}
var hasMicrophone=!1;var hasSpeakers=!1;var hasWebcam=!1;var isWebsiteHasMicrophonePermissions=!1;var isWebsiteHasWebcamPermissions=!1;function checkDeviceSupport(callback){if(!canEnumerate){if(callback){callback()}
return}
if(!navigator.enumerateDevices&&window.MediaStreamTrack&&window.MediaStreamTrack.getSources){navigator.enumerateDevices=window.MediaStreamTrack.getSources.bind(window.MediaStreamTrack)}
if(!navigator.enumerateDevices&&navigator.enumerateDevices){navigator.enumerateDevices=navigator.enumerateDevices.bind(navigator)}
if(!navigator.enumerateDevices){if(callback){callback()}
return}
MediaDevices=[];audioInputDevices=[];audioOutputDevices=[];videoInputDevices=[];hasMicrophone=!1;hasSpeakers=!1;hasWebcam=!1;isWebsiteHasMicrophonePermissions=!1;isWebsiteHasWebcamPermissions=!1;var alreadyUsedDevices={};navigator.enumerateDevices(function(devices){devices.forEach(function(_device){var device={};for(var d in _device){try{if(typeof _device[d]!=='function'){device[d]=_device[d]}}catch(e){}}
if(alreadyUsedDevices[device.deviceId+device.label]){return}
if(device.kind==='audio'){device.kind='audioinput'}
if(device.kind==='video'){device.kind='videoinput'}
if(!device.deviceId){device.deviceId=device.id}
if(!device.id){device.id=device.deviceId}
if(!device.label){device.label='Please invoke getUserMedia once.';if(typeof DetectRTC!=='undefined'&&DetectRTC.browser.isChrome&&DetectRTC.browser.version>=46&&!/^(https:|chrome-extension:)$/g.test(location.protocol||'')){if(typeof document!=='undefined'&&typeof document.domain==='string'&&document.domain.search&&document.domain.search(/localhost|127.0./g)===-1){device.label='HTTPs is required to get label of this '+device.kind+' device.'}}}else{if(device.kind==='videoinput'&&!isWebsiteHasWebcamPermissions){isWebsiteHasWebcamPermissions=!0}
if(device.kind==='audioinput'&&!isWebsiteHasMicrophonePermissions){isWebsiteHasMicrophonePermissions=!0}}
if(device.kind==='audioinput'){hasMicrophone=!0;if(audioInputDevices.indexOf(device)===-1){audioInputDevices.push(device)}}
if(device.kind==='audiooutput'){hasSpeakers=!0;if(audioOutputDevices.indexOf(device)===-1){audioOutputDevices.push(device)}}
if(device.kind==='videoinput'){hasWebcam=!0;if(videoInputDevices.indexOf(device)===-1){videoInputDevices.push(device)}}
MediaDevices.push(device);alreadyUsedDevices[device.deviceId+device.label]=device});if(typeof DetectRTC!=='undefined'){DetectRTC.MediaDevices=MediaDevices;DetectRTC.hasMicrophone=hasMicrophone;DetectRTC.hasSpeakers=hasSpeakers;DetectRTC.hasWebcam=hasWebcam;DetectRTC.isWebsiteHasWebcamPermissions=isWebsiteHasWebcamPermissions;DetectRTC.isWebsiteHasMicrophonePermissions=isWebsiteHasMicrophonePermissions;DetectRTC.audioInputDevices=audioInputDevices;DetectRTC.audioOutputDevices=audioOutputDevices;DetectRTC.videoInputDevices=videoInputDevices}
if(callback){callback()}})}
var DetectRTC=window.DetectRTC||{};DetectRTC.browser=getBrowserInfo();detectPrivateMode(function(isPrivateBrowsing){DetectRTC.browser.isPrivateBrowsing=!!isPrivateBrowsing});DetectRTC.browser['is'+DetectRTC.browser.name]=!0;DetectRTC.osName=osName;DetectRTC.osVersion=osVersion;var isNodeWebkit=typeof process==='object'&&typeof process.versions==='object'&&process.versions['node-webkit'];var isWebRTCSupported=!1;['RTCPeerConnection','webkitRTCPeerConnection','mozRTCPeerConnection','RTCIceGatherer'].forEach(function(item){if(isWebRTCSupported){return}
if(item in window){isWebRTCSupported=!0}});DetectRTC.isWebRTCSupported=isWebRTCSupported;DetectRTC.isORTCSupported=typeof RTCIceGatherer!=='undefined';var isScreenCapturingSupported=!1;if(DetectRTC.browser.isChrome&&DetectRTC.browser.version>=35){isScreenCapturingSupported=!0}else if(DetectRTC.browser.isFirefox&&DetectRTC.browser.version>=34){isScreenCapturingSupported=!0}
if(!/^(https:|chrome-extension:)$/g.test(location.protocol||'')){if(typeof document!=='undefined'&&typeof document.domain==='string'&&document.domain.search&&document.domain.search(/localhost|127.0./g)===-1){isScreenCapturingSupported=!1}
if(DetectRTC.browser.isFirefox){isScreenCapturingSupported=!1}}
DetectRTC.isScreenCapturingSupported=isScreenCapturingSupported;var webAudio={isSupported:!1,isCreateMediaStreamSourceSupported:!1};['AudioContext','webkitAudioContext','mozAudioContext','msAudioContext'].forEach(function(item){if(webAudio.isSupported){return}
if(item in window){webAudio.isSupported=!0;if(window[item]&&'createMediaStreamSource' in window[item].prototype){webAudio.isCreateMediaStreamSourceSupported=!0}}});DetectRTC.isAudioContextSupported=webAudio.isSupported;DetectRTC.isCreateMediaStreamSourceSupported=webAudio.isCreateMediaStreamSourceSupported;var isRtpDataChannelsSupported=!1;if(DetectRTC.browser.isChrome&&DetectRTC.browser.version>31){isRtpDataChannelsSupported=!0}
DetectRTC.isRtpDataChannelsSupported=isRtpDataChannelsSupported;var isSCTPSupportd=!1;if(DetectRTC.browser.isFirefox&&DetectRTC.browser.version>28){isSCTPSupportd=!0}else if(DetectRTC.browser.isChrome&&DetectRTC.browser.version>25){isSCTPSupportd=!0}else if(DetectRTC.browser.isOpera&&DetectRTC.browser.version>=11){isSCTPSupportd=!0}
DetectRTC.isSctpDataChannelsSupported=isSCTPSupportd;DetectRTC.isMobileDevice=isMobileDevice;var isGetUserMediaSupported=!1;if(navigator.getUserMedia){isGetUserMediaSupported=!0}else if(navigator.mediaDevices&&navigator.mediaDevices.getUserMedia){isGetUserMediaSupported=!0}
if(DetectRTC.browser.isChrome&&DetectRTC.browser.version>=46&&!/^(https:|chrome-extension:)$/g.test(location.protocol||'')){if(typeof document!=='undefined'&&typeof document.domain==='string'&&document.domain.search&&document.domain.search(/localhost|127.0./g)===-1){isGetUserMediaSupported='Requires HTTPs'}}
if(DetectRTC.osName==='Nodejs'){isGetUserMediaSupported=!1}
DetectRTC.isGetUserMediaSupported=isGetUserMediaSupported;var displayResolution='';if(screen.width){var width=(screen.width)?screen.width:'';var height=(screen.height)?screen.height:'';displayResolution+=''+width+' x '+height}
DetectRTC.displayResolution=displayResolution;DetectRTC.isCanvasSupportsStreamCapturing=isCanvasSupportsStreamCapturing;DetectRTC.isVideoSupportsStreamCapturing=isVideoSupportsStreamCapturing;if(DetectRTC.browser.name=='Chrome'&&DetectRTC.browser.version>=53){if(!DetectRTC.isCanvasSupportsStreamCapturing){DetectRTC.isCanvasSupportsStreamCapturing='Requires chrome flag: enable-experimental-web-platform-features'}
if(!DetectRTC.isVideoSupportsStreamCapturing){DetectRTC.isVideoSupportsStreamCapturing='Requires chrome flag: enable-experimental-web-platform-features'}}
DetectRTC.DetectLocalIPAddress=DetectLocalIPAddress;DetectRTC.isWebSocketsSupported='WebSocket' in window&&2===window.WebSocket.CLOSING;DetectRTC.isWebSocketsBlocked=!DetectRTC.isWebSocketsSupported;if(DetectRTC.osName==='Nodejs'){DetectRTC.isWebSocketsSupported=!0;DetectRTC.isWebSocketsBlocked=!1}
DetectRTC.checkWebSocketsSupport=function(callback){callback=callback||function(){};try{var websocket=new WebSocket('wss://echo.websocket.org:443/');websocket.onopen=function(){DetectRTC.isWebSocketsBlocked=!1;callback();websocket.close();websocket=null};websocket.onerror=function(){DetectRTC.isWebSocketsBlocked=!0;callback()}}catch(e){DetectRTC.isWebSocketsBlocked=!0;callback()}};DetectRTC.load=function(callback){callback=callback||function(){};checkDeviceSupport(callback)};if(typeof checkDeviceSupport==='function'){}
if(typeof MediaDevices!=='undefined'){DetectRTC.MediaDevices=MediaDevices}else{DetectRTC.MediaDevices=[]}
DetectRTC.hasMicrophone=hasMicrophone;DetectRTC.hasSpeakers=hasSpeakers;DetectRTC.hasWebcam=hasWebcam;DetectRTC.isWebsiteHasWebcamPermissions=isWebsiteHasWebcamPermissions;DetectRTC.isWebsiteHasMicrophonePermissions=isWebsiteHasMicrophonePermissions;DetectRTC.audioInputDevices=audioInputDevices;DetectRTC.audioOutputDevices=audioOutputDevices;DetectRTC.videoInputDevices=videoInputDevices;var isSetSinkIdSupported=!1;if(typeof document!=='undefined'&&typeof document.createElement==='function'&&'setSinkId' in document.createElement('video')){isSetSinkIdSupported=!0}
DetectRTC.isSetSinkIdSupported=isSetSinkIdSupported;var isRTPSenderReplaceTracksSupported=!1;if(DetectRTC.browser.isFirefox&&typeof mozRTCPeerConnection!=='undefined'){if('getSenders' in mozRTCPeerConnection.prototype){isRTPSenderReplaceTracksSupported=!0}}else if(DetectRTC.browser.isChrome&&typeof webkitRTCPeerConnection!=='undefined'){if('getSenders' in webkitRTCPeerConnection.prototype){isRTPSenderReplaceTracksSupported=!0}}
DetectRTC.isRTPSenderReplaceTracksSupported=isRTPSenderReplaceTracksSupported;var isRemoteStreamProcessingSupported=!1;if(DetectRTC.browser.isFirefox&&DetectRTC.browser.version>38){isRemoteStreamProcessingSupported=!0}
DetectRTC.isRemoteStreamProcessingSupported=isRemoteStreamProcessingSupported;var isApplyConstraintsSupported=!1;if(typeof MediaStreamTrack!=='undefined'&&'applyConstraints' in MediaStreamTrack.prototype){isApplyConstraintsSupported=!0}
DetectRTC.isApplyConstraintsSupported=isApplyConstraintsSupported;var isMultiMonitorScreenCapturingSupported=!1;if(DetectRTC.browser.isFirefox&&DetectRTC.browser.version>=43){isMultiMonitorScreenCapturingSupported=!0}
DetectRTC.isMultiMonitorScreenCapturingSupported=isMultiMonitorScreenCapturingSupported;DetectRTC.isPromisesSupported=!!('Promise' in window);if(typeof DetectRTC==='undefined'){window.DetectRTC={}}
var MediaStream=window.MediaStream;if(typeof MediaStream==='undefined'&&typeof webkitMediaStream!=='undefined'){MediaStream=webkitMediaStream}
if(typeof MediaStream!=='undefined'){DetectRTC.MediaStream=Object.keys(MediaStream.prototype)}else DetectRTC.MediaStream=!1;if(typeof MediaStreamTrack!=='undefined'){DetectRTC.MediaStreamTrack=Object.keys(MediaStreamTrack.prototype)}else DetectRTC.MediaStreamTrack=!1;var RTCPeerConnection=window.RTCPeerConnection||window.mozRTCPeerConnection||window.webkitRTCPeerConnection;if(typeof RTCPeerConnection!=='undefined'){DetectRTC.RTCPeerConnection=Object.keys(RTCPeerConnection.prototype)}else DetectRTC.RTCPeerConnection=!1;window.DetectRTC=DetectRTC;if(typeof module!=='undefined'){module.exports=DetectRTC}
if(typeof define==='function'&&define.amd){define('DetectRTC',[],function(){return DetectRTC})}})()