
package com.rank.ccms.ws.guest;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "VidyoPortalGuestService", targetNamespace = "http://portal.vidyo.com/guest", wsdlLocation = "https://vcportal.ranktechsolutions.com/services/VidyoPortalGuestService?wsdl")
public class VidyoPortalGuestService
    extends Service
{

    private final static URL VIDYOPORTALGUESTSERVICE_WSDL_LOCATION;
    private final static WebServiceException VIDYOPORTALGUESTSERVICE_EXCEPTION;
    private final static QName VIDYOPORTALGUESTSERVICE_QNAME = new QName("http://portal.vidyo.com/guest", "VidyoPortalGuestService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://vcportal.ranktechsolutions.com/services/VidyoPortalGuestService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        VIDYOPORTALGUESTSERVICE_WSDL_LOCATION = url;
        VIDYOPORTALGUESTSERVICE_EXCEPTION = e;
    }

    public VidyoPortalGuestService() {
        super(__getWsdlLocation(), VIDYOPORTALGUESTSERVICE_QNAME);
    }

    public VidyoPortalGuestService(WebServiceFeature... features) {
        super(__getWsdlLocation(), VIDYOPORTALGUESTSERVICE_QNAME, features);
    }

    public VidyoPortalGuestService(URL wsdlLocation) {
        super(wsdlLocation, VIDYOPORTALGUESTSERVICE_QNAME);
    }

    public VidyoPortalGuestService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, VIDYOPORTALGUESTSERVICE_QNAME, features);
    }

    public VidyoPortalGuestService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public VidyoPortalGuestService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns VidyoPortalGuestServicePortType
     */
    @WebEndpoint(name = "VidyoPortalGuestServicePort")
    public VidyoPortalGuestServicePortType getVidyoPortalGuestServicePort() {
        return super.getPort(new QName("http://portal.vidyo.com/guest", "VidyoPortalGuestServicePort"), VidyoPortalGuestServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns VidyoPortalGuestServicePortType
     */
    @WebEndpoint(name = "VidyoPortalGuestServicePort")
    public VidyoPortalGuestServicePortType getVidyoPortalGuestServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://portal.vidyo.com/guest", "VidyoPortalGuestServicePort"), VidyoPortalGuestServicePortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (VIDYOPORTALGUESTSERVICE_EXCEPTION!= null) {
            throw VIDYOPORTALGUESTSERVICE_EXCEPTION;
        }
        return VIDYOPORTALGUESTSERVICE_WSDL_LOCATION;
    }

}
