
package com.rank.ccms.ws.guest;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "VidyoPortalGuestServicePortType", targetNamespace = "http://portal.vidyo.com/guest")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface VidyoPortalGuestServicePortType {


    /**
     * 
     * @param parameter
     * @return
     *     returns com.rank.ibl.ws.guest.LogInAsGuestResponse
     * @throws InvalidArgumentFault_Exception
     * @throws ResourceNotAvailableFault_Exception
     * @throws GeneralFault_Exception
     * @throws RoomIsFullFault_Exception
     */
    @WebMethod(action = "logInAsGuest")
    @WebResult(name = "LogInAsGuestResponse", targetNamespace = "http://portal.vidyo.com/guest", partName = "parameter")
    public LogInAsGuestResponse logInAsGuest(
        @WebParam(name = "LogInAsGuestRequest", targetNamespace = "http://portal.vidyo.com/guest", partName = "parameter")
        LogInAsGuestRequest parameter)
        throws GeneralFault_Exception, InvalidArgumentFault_Exception, ResourceNotAvailableFault_Exception, RoomIsFullFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.rank.ibl.ws.guest.LinkEndpointToGuestResponse
     * @throws AccessRestrictedFault_Exception
     * @throws InvalidArgumentFault_Exception
     * @throws GeneralFault_Exception
     */
    @WebMethod(action = "linkEndpointToGuest")
    @WebResult(name = "LinkEndpointToGuestResponse", targetNamespace = "http://portal.vidyo.com/guest", partName = "parameter")
    public LinkEndpointToGuestResponse linkEndpointToGuest(
        @WebParam(name = "LinkEndpointToGuestRequest", targetNamespace = "http://portal.vidyo.com/guest", partName = "parameter")
        LinkEndpointToGuestRequest parameter)
        throws AccessRestrictedFault_Exception, GeneralFault_Exception, InvalidArgumentFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.rank.ibl.ws.guest.SetEndpointDetailsResponse
     * @throws EndpointNotBoundFault_Exception
     * @throws InvalidArgumentFault_Exception
     * @throws GeneralFault_Exception
     */
    @WebMethod(action = "setEndpointDetails")
    @WebResult(name = "SetEndpointDetailsResponse", targetNamespace = "http://portal.vidyo.com/guest", partName = "parameter")
    public SetEndpointDetailsResponse setEndpointDetails(
        @WebParam(name = "SetEndpointDetailsRequest", targetNamespace = "http://portal.vidyo.com/guest", partName = "parameter")
        SetEndpointDetailsRequest parameter)
        throws EndpointNotBoundFault_Exception, GeneralFault_Exception, InvalidArgumentFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.rank.ibl.ws.guest.GuestJoinConferenceResponse
     * @throws ConferenceLockedFault_Exception
     * @throws WrongPinFault_Exception
     * @throws ResourceNotAvailableFault_Exception
     * @throws InvalidArgumentFault_Exception
     * @throws AllLinesInUseFault_Exception
     * @throws GeneralFault_Exception
     * @throws RoomIsFullFault_Exception
     */
    @WebMethod(action = "guestJoinConference")
    @WebResult(name = "GuestJoinConferenceResponse", targetNamespace = "http://portal.vidyo.com/guest", partName = "parameter")
    public GuestJoinConferenceResponse guestJoinConference(
        @WebParam(name = "GuestJoinConferenceRequest", targetNamespace = "http://portal.vidyo.com/guest", partName = "parameter")
        GuestJoinConferenceRequest parameter)
        throws AllLinesInUseFault_Exception, ConferenceLockedFault_Exception, GeneralFault_Exception, InvalidArgumentFault_Exception, ResourceNotAvailableFault_Exception, RoomIsFullFault_Exception, WrongPinFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.rank.ibl.ws.guest.GetPortalVersionResponse
     * @throws GeneralFault_Exception
     */
    @WebMethod(action = "getPortalVersion")
    @WebResult(name = "GetPortalVersionResponse", targetNamespace = "http://portal.vidyo.com/guest", partName = "parameter")
    public GetPortalVersionResponse getPortalVersion(
        @WebParam(name = "GetPortalVersionRequest", targetNamespace = "http://portal.vidyo.com/guest", partName = "parameter")
        Object parameter)
        throws GeneralFault_Exception
    ;

    /**
     * Get the current active client version
     * 
     * @param parameter
     * @return
     *     returns com.rank.ibl.ws.guest.ClientVersionResponse
     * @throws InvalidArgumentFault_Exception
     * @throws GeneralFault_Exception
     */
    @WebMethod(action = "getClientVersion")
    @WebResult(name = "ClientVersionResponse", targetNamespace = "http://portal.vidyo.com/guest", partName = "parameter")
    public ClientVersionResponse getClientVersion(
        @WebParam(name = "ClientVersionRequest", targetNamespace = "http://portal.vidyo.com/guest", partName = "parameter")
        ClientVersionRequest parameter)
        throws GeneralFault_Exception, InvalidArgumentFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.rank.ibl.ws.guest.GetPortalFeaturesResponse
     * @throws GeneralFault_Exception
     */
    @WebMethod(action = "getPortalFeatures")
    @WebResult(name = "GetPortalFeaturesResponse", targetNamespace = "http://portal.vidyo.com/guest", partName = "parameter")
    public GetPortalFeaturesResponse getPortalFeatures(
        @WebParam(name = "GetPortalFeaturesRequest", targetNamespace = "http://portal.vidyo.com/guest", partName = "parameter")
        Object parameter)
        throws GeneralFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.rank.ibl.ws.guest.RaiseHandResponse
     * @throws InvalidArgumentFault_Exception
     * @throws GeneralFault_Exception
     */
    @WebMethod(action = "raiseHand")
    @WebResult(name = "RaiseHandResponse", targetNamespace = "http://portal.vidyo.com/guest", partName = "parameter")
    public RaiseHandResponse raiseHand(
        @WebParam(name = "RaiseHandRequest", targetNamespace = "http://portal.vidyo.com/guest", partName = "parameter")
        RaiseHandRequest parameter)
        throws GeneralFault_Exception, InvalidArgumentFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.rank.ibl.ws.guest.UnraiseHandResponse
     * @throws InvalidArgumentFault_Exception
     * @throws GeneralFault_Exception
     */
    @WebMethod(action = "unraiseHand")
    @WebResult(name = "UnraiseHandResponse", targetNamespace = "http://portal.vidyo.com/guest", partName = "parameter")
    public UnraiseHandResponse unraiseHand(
        @WebParam(name = "UnraiseHandRequest", targetNamespace = "http://portal.vidyo.com/guest", partName = "parameter")
        UnraiseHandRequest parameter)
        throws GeneralFault_Exception, InvalidArgumentFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.rank.ibl.ws.guest.RecoverPasswordResponse
     * @throws EmailAddressNotFoundFault_Exception
     * @throws GeneralFault_Exception
     * @throws NotificationEmailNotConfiguredFault_Exception
     */
    @WebMethod(action = "recoverPassword")
    @WebResult(name = "RecoverPasswordResponse", targetNamespace = "http://portal.vidyo.com/guest", partName = "parameter")
    public RecoverPasswordResponse recoverPassword(
        @WebParam(name = "RecoverPasswordRequest", targetNamespace = "http://portal.vidyo.com/guest", partName = "parameter")
        RecoverPasswordRequest parameter)
        throws EmailAddressNotFoundFault_Exception, GeneralFault_Exception, NotificationEmailNotConfiguredFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.rank.ibl.ws.guest.WhatIsMyIPAddressResponse
     * @throws GeneralFault_Exception
     */
    @WebMethod(action = "whatIsMyIPAddress")
    @WebResult(name = "WhatIsMyIPAddressResponse", targetNamespace = "http://portal.vidyo.com/guest", partName = "parameter")
    public WhatIsMyIPAddressResponse whatIsMyIPAddress(
        @WebParam(name = "WhatIsMyIPAddressRequest", targetNamespace = "http://portal.vidyo.com/guest", partName = "parameter")
        WhatIsMyIPAddressRequest parameter)
        throws GeneralFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.rank.ibl.ws.guest.CreateTestcallRoomResponse
     * @throws TestcallRoomCreationFault_Exception
     * @throws GeneralFault_Exception
     */
    @WebMethod(action = "createTestcallRoom")
    @WebResult(name = "CreateTestcallRoomResponse", targetNamespace = "http://portal.vidyo.com/guest", partName = "parameter")
    public CreateTestcallRoomResponse createTestcallRoom(
        @WebParam(name = "CreateTestcallRoomRequest", targetNamespace = "http://portal.vidyo.com/guest", partName = "parameter")
        Object parameter)
        throws GeneralFault_Exception, TestcallRoomCreationFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.rank.ibl.ws.guest.GetRoomDetailsByRoomKeyResponse
     * @throws InvalidArgumentFault_Exception
     * @throws ResourceNotAvailableFault_Exception
     * @throws GeneralFault_Exception
     */
    @WebMethod(action = "getRoomDetailsByRoomKey")
    @WebResult(name = "GetRoomDetailsByRoomKeyResponse", targetNamespace = "http://portal.vidyo.com/guest", partName = "parameter")
    public GetRoomDetailsByRoomKeyResponse getRoomDetailsByRoomKey(
        @WebParam(name = "GetRoomDetailsByRoomKeyRequest", targetNamespace = "http://portal.vidyo.com/guest", partName = "parameter")
        GetRoomDetailsByRoomKeyRequest parameter)
        throws GeneralFault_Exception, InvalidArgumentFault_Exception, ResourceNotAvailableFault_Exception
    ;

}
